### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by minehostil** [Endxxr/AdvancedAbilities#2]
I have some errors in the new version, in the switcher and blindness egg items the cooldown is not fulfilled, in the other items such as the stun or anti-build and in the others it does not execute the actions and when interacting with them those errors appear in the console. 

I have lightspigot and java 8

Console error  https://pastebin.com/CfnaDwCq

**Comment by Antoniova1** [comment]
images where the cooldown is not respected
![20230814_215020](https://github.com/Endxxr/AdvancedAbilities/assets/108409110/0dd27cb7-2509-4d4f-98f7-220c507091f3)
![Uploading 20230814_213518.png…]()

**Comment by Antoniova1** [comment]
images where the cooldown is not respected

![20230814_213518](https://github.com/Endxxr/AdvancedAbilities/assets/108409110/94aeb545-8185-4add-ab7a-a95463b598a9)
![20230814_215020](https://github.com/Endxxr/AdvancedAbilities/assets/108409110/df09fc80-f2ad-4ab0-8dfd-2f748fd29dd6)

**Comment by minehostil** [comment]
images where the cooldown is not respected
![20230814_215011](https://github.com/Endxxr/AdvancedAbilities/assets/108409110/56c360ab-dc9d-4f81-b573-72962af87931)
![20230814_215020](https://github.com/Endxxr/AdvancedAbilities/assets/108409110/da9a511b-a03b-49c0-8daf-f438acef5f84)

**Comment by Endxxr** [comment]
Hey, thank you for reaching out. The two errors are correlated. I'm releasing a patch today.

**Comment by Endxxr** [comment]
Patch released!
https://github.com/Endxxr/AdvancedAbilities/releases/download/v4.1.2/AdvancedAbilities-4.1.2-STABLE.jar
