### ISSUE TITLE
cooldown is not respected

### ISSUE THREAD

**Issue by minehostil** [Endxxr/AdvancedAbilities#3]
the items are removed even when the cooldown is active, it happens with all the items, except the leap and Invulnerability
V4.1.2
I use lightspigot java 8

![20230817_121748](https://github.com/Endxxr/AdvancedAbilities/assets/108409110/95ed970a-ef2f-455c-b2a8-705a3a4194f1)
![20230817_121822](https://github.com/Endxxr/AdvancedAbilities/assets/108409110/3c05117e-5de6-44a5-acc6-1e9d8a645720)

**Comment by Endxxr** [comment]
Any error?

**Comment by minehostil** [comment]
no console errors on these abilities, stun, anti build, rotten egg, pot counter, Invulnerability, leap, switcher and bamboozle, those are the ones I'm currently using

**Comment by minehostil** [comment]
in testing and testing I have only seen this error
![20230817_230318](https://github.com/Endxxr/AdvancedAbilities/assets/108409110/d5ee4d92-e074-483b-937e-ac1a17639499)

**Comment by Endxxr** [comment]
Checking

**Comment by Endxxr** [comment]
Releasing a patch this night

**Comment by minehostil** [comment]
Ty ty

**Comment by Endxxr** [comment]
Patch released
